pipeline {
  agent any

  environment {
    VAULT_ADDR = 'http://172.17.0.2:8200'
    VAULT_TOKEN=credentials("VAULT_TOKEN")
  }

  stages {
    stage ('Compile Stage') {
      steps {
        sh "vault read aws/creds/storage_manager_role -format=json"
      }
    }
  }

  
}
