pipeline {
  agent any

  environment {
    VAULT_ADDR = 'http://172.17.0.2:8200'
    VAULT_TOKEN=credentials("VAULT_TOKEN")
  }

  stages {
    stage ('Vault Stage') {
      steps {
        sh """
          set +x
          export TOKEN=`vault read aws/creds/storage_manager_role -format=json`
          export AWS_ACCESS_KEY_ID=`echo \$TOKEN | jq -r ."data" | jq -r ."access_key")`
          export AWS_SECRET_ACCESS_KEY=`echo \$TOKEN | jq -r ."data" | jq -r ."secret_key")`
          aws s3 ls --region eu-central-1
        """
      }
    }
  }

  
}
